### ISSUE TITLE
Legacy or previously removed link to record still preserved?

### ISSUE THREAD

**Issue by mhaidarhanif** [kontenbase/feedback#3]
Found that the lookup the link to other records are still preserving the legacy link (legacy).

Is this intended or a bug?

This is the URL:

```
https://api.kontenbase.com/query/api/v1/ca5983bb-eaad-478f-9390-85e5ace4ddb4/Posts?%24lookup=authors
```

The object looks like this:

```json
{
    "_id": "61c1dd8a2a43d87ac4518ec8",
    "title": "The rise of Tesla",
    "description": "Story about the rise of Tesla.",
    "authors": [
      {
        "name": "Elon Musk",
        "avatar": [
          {
            "fileName": "elonmusk.jpg",
            "url": "https://api.kontenbase.com/upload/file/61c1dc392a43d87ac4518e96/hHYlfAeHlDwyEja/elonmusk.jpg"
          }
        ],
        "_rank": "U",
        "Posts": [
          
        ],
        "posts": [
          "61c1dd8a2a43d87ac4518ec8"
        ],
        "blog": [
          
        ],
        "blogs 1": [
          
        ],
        "Movies 1": [
          
        ],
        "post": [
          
        ]
      }
    ]
  },
```

What expected would be just show `posts`, but there are also `Posts`, `blog`, `blogs 1`, `Movies 1`, `post` which should already been removed.

**Comment by mhaidarhanif** [comment]
Screenshots:

<img width="1083" alt="Screen Shot 2022-01-06 at 05 33 15" src="https://user-images.githubusercontent.com/235584/148299104-e8ab27a1-267f-420a-86e6-11ee892276ad.png">

<img width="1108" alt="Screen Shot 2022-01-06 at 05 33 31" src="https://user-images.githubusercontent.com/235584/148299166-3f5e6fdd-1fe4-4ec2-a7ea-b95a4c15183b.png">

<img width="1101" alt="Screen Shot 2022-01-06 at 05 33 40" src="https://user-images.githubusercontent.com/235584/148299178-35cebb40-13f1-4486-bb04-969a971be232.png">

<img width="1100" alt="Screen Shot 2022-01-06 at 05 33 48" src="https://user-images.githubusercontent.com/235584/148299180-a7288447-3699-48f4-825a-ee24f9c66021.png">

**Comment by exneval** [comment]
Hi there, thank you for reporting the feedback with such details.
We were able to produce and work hard to fix the issue.
Please wait for updates, thank you.

**Comment by exneval** [comment]
Update:
The issue should have been fixed by now, I will close this issue.
Please try it and report back if it's still there so we can open this issue again.
Thanks

**Comment by mhaidarhanif** [comment]
Thanks @exneval it works better now 👍
