### ISSUE TITLE
Unable to login in macOS Safari

### ISSUE THREAD

**Issue by zainfathoni** [kontenbase/feedback#4]
# Bug report

## Describe the bug

Unable to login in macOS Safari.

## To Reproduce

- **Given** I am a non-authenticated user,
- **when** I open dashboard login page in **macOS Safari** browser,
- **and** click **Continue with Google** button,
- **then** I am prompted to choose an account,
- **when** I clicked one of the accounts,
- **then** I am redirected back to dashboard login page,
- **and** presented with a **Continue with Google** button again.

It happens infinitely

## Expected behavior

- **Given** I am a non-authenticated user,
- **when** I open dashboard login page in **macOS Safari** browser,
- **and** click **Continue with Google** button,
- **then** I am prompted to choose an account,
- **when** I clicked one of the accounts,
- **then** I am authenticated successfully,
- **and** redirected to the Kontenbase dashboard.

## Screenshots

~

## System information

- OS: mac
- Browser: safari

## Additional context

~

**Comment by exneval** [comment]
hi @zainfathoni, thank you for reporting the issue, I will look into this.

Just want to make sure, have you tried with other browsers? Did you also find this issue with them?

**Comment by zainfathoni** [comment]
> hi @zainfathoni, thank you for reporting the issue, I will look into this.
> 
> Just want to make sure, have you tried with other browsers? Did you also find this issue with them?

Yes, I tried with another browser (Brave Browser) and it worked. 😁

**Comment by exneval** [comment]
Turned out Safari has an issue with google redirect ux_mode:
- https://github.com/google/google-api-javascript-client/issues/566
- https://github.com/google/google-api-javascript-client/issues/490

So unlike other browsers, Safari will use popup mode for kontenbase google login.
Fixed it in the dashboard. Thank you.

**Comment by zainfathoni** [comment]
I tried it again, and it works now, nice!
Thanks for fixing it.
