### ISSUE TITLE
Navigation menu styling bug

### ISSUE THREAD

**Issue by xirf** [kontenbase/feedback#6]
# Bug report

## Describe the bug
I found some bug on kontenbase website, the side nav isn't well styled on smartphone. 

## Screenshots

![Screenshot_2022_0317_055738](https://user-images.githubusercontent.com/55616872/158704875-6678e1ab-df3e-42c1-9960-f5ab7c1895cb.jpg)

## System information

- OS: Android 10
- Browser: Embed Chrome
- Device: Vivo y20
- Screen Res: 360x800 pixel

**Comment by exneval** [comment]
Hi, thank you for finding it. We are working on a complete website revamp. Please wait for it.

**Comment by mhaidarhanif** [comment]
@evaasmakula Thank you for reporting the styling bug on the navigation menu.

In the meantime as mentioned by @exneval, we are working on a new website revamp that you can preview here: https://v1.kontenbase.com

So once the new one is published, this issue will be closed. Thanks!

**Comment by mhaidarhanif** [comment]
As the v1 site has already published. This is no longer relevant.
